castellum/execution/urls.py
# (c) 2018-2023 MPIB <https://www.mpib-berlin.mpg.de/>,
#     2018-2019 MPI-CBS <https://www.cbs.mpg.de/>,
#     2018-2019 MPIP <http://www.psych.mpg.de/>
#
# This file is part of Castellum.
#
# Castellum is free software; you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# Castellum is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License along with Castellum. If not, see
# <http://www.gnu.org/licenses/>.

from django.conf import settings
from django.urls import path

from .api import APIAttributesView
from .api import APIDomainsView
from .api import APIPseudonymsView
from .api import APIResolveView
from .api import APIValidateView
from .feeds import AppointmentFeedForStudy
from .feeds import AppointmentFeedForUser
from .feeds import ResourceFeed
from .views import AdditionalInfoUpdateView
from .views import AttributesUpdateView
from .views import CalendarView
from .views import ConsentChangeView
from .views import ContactUpdateView
from .views import DataProtectionUpdateView
from .views import ExclusionCriteriaView
from .views import ExportView
from .views import LegalRepresentativeContactUpdateView
from .views import NewsMailView
from .views import ParticipationAppointmentsUpdateView
from .views import ParticipationConsentUpdateView
from .views import ParticipationConsentView
from .views import ParticipationDetailView
from .views import ParticipationDropoutConfirmView
from .views import ParticipationDropoutView
from .views import ParticipationListView
from .views import ParticipationPseudonymsView
from .views import ParticipationPseudonymView
from .views import ParticipationUpdateView
from .views import ProgressView
from .views import ResolveView
from .views import TagView

app_name = 'execution'
urlpatterns = [
    path('calendar/feed/', AppointmentFeedForUser.as_view(), name='calendar-user-feed'),
    path('resources/<int:pk>/', ResourceFeed.as_view(), name='resource-feed'),
    path('<int:study_pk>/', ParticipationListView.as_view(), name='participation-list'),
    path('<int:study_pk>/resolve/', ResolveView.as_view(), name='resolve'),
    path('<int:study_pk>/news/', NewsMailView.as_view(), name='news-mail'),
    path('<int:pk>/calendar/', CalendarView.as_view(), name='calendar'),
    path('<int:pk>/calendar/feed/', AppointmentFeedForStudy.as_view(), name='calendar-feed'),
    path('<int:pk>/criteria/', ExclusionCriteriaView.as_view(), name='criteria'),
    path('<int:pk>/export/', ExportView.as_view(), name='export'),
    path('<int:pk>/progress/', ProgressView.as_view(), name='progress'),
    path('<int:pk>/tags/', TagView.as_view(), name='execution-tags'),
    path(
        '<int:study_pk>/<int:pk>/',
        ParticipationDetailView.as_view(),
        name='participation-detail',
    ),
    path(
        '<int:study_pk>/<int:pk>/pseudonyms/',
        ParticipationPseudonymsView.as_view(),
        name='participation-pseudonyms',
    ),
    path(
        '<int:study_pk>/<int:pk>/pseudonyms/<domain>/',
        ParticipationPseudonymView.as_view(),
        name='participation-pseudonym',
    ),
    path(
        '<int:study_pk>/<int:pk>/dropout/',
        ParticipationDropoutView.as_view(),
        name='participation-dropout',
    ),
    path(
        '<int:study_pk>/<int:pk>/dropout/confirm/',
        ParticipationDropoutConfirmView.as_view(),
        name='participation-dropout-confirm',
    ),
    path(
        '<int:study_pk>/<int:pk>/update/',
        ParticipationUpdateView.as_view(),
        name='participation-update',
    ),
    path(
        '<int:study_pk>/<int:pk>/consent/',
        ParticipationConsentView.as_view(),
        name='participation-consent',
    ),
    path(
        '<int:study_pk>/<int:pk>/consent/change/',
        ParticipationConsentUpdateView.as_view(),
        name='participation-consent-change',
    ),
    path(
        '<int:study_pk>/<int:pk>/appointments/',
        ParticipationAppointmentsUpdateView.as_view(),
        name='participation-appointments',
    ),
    path(
        '<int:study_pk>/<int:pk>/update-contact/',
        ContactUpdateView.as_view(),
        name='contact-update',
    ),
    path(
        '<int:study_pk>/<int:pk>/update-attributes/',
        AttributesUpdateView.as_view(),
        name='attributes-update',
    ),
    path(
        '<int:study_pk>/<int:pk>/update-data-protection/',
        DataProtectionUpdateView.as_view(),
        name='data-protection-update',
    ),
    path(
        '<int:study_pk>/<int:pk>/update-data-protection/consent/',
        ConsentChangeView.as_view(),
        name='consent-change',
    ),
    path(
        '<int:study_pk>/<int:pk>/update-additional-info/',
        AdditionalInfoUpdateView.as_view(),
        name='additional-info-update',
    ),
    path(
        '<int:study_pk>/<int:participation_pk>/representatives/<hash>/update-contact/',
        LegalRepresentativeContactUpdateView.as_view(),
        name='legal-representative-contact-update',
    ),
]

if settings.CASTELLUM_API_ENABLED:
    urlpatterns += [
        path('api/studies/<int:pk>/domains/', APIDomainsView.as_view()),
        path('api/studies/<int:pk>/domains/<uuid:domain>/', APIPseudonymsView.as_view()),
        path('api/studies/<int:pk>/domains/<uuid:domain>/<pseudonym>/', APIValidateView.as_view()),
        path(
            'api/studies/<int:study_pk>/domains/<uuid:domain>/<pseudonym>/attributes/',
            APIAttributesView.as_view(),
        ),
        path(
            'api/studies/<int:study_pk>/domains/<uuid:domain>/<pseudonym>/<uuid:target_domain>/',
            APIResolveView.as_view(),
        ),
    ]

castellum/urls.py
# (c) 2018-2023 MPIB <https://www.mpib-berlin.mpg.de/>,
#     2018-2019 MPI-CBS <https://www.cbs.mpg.de/>,
#     2018-2019 MPIP <http://www.psych.mpg.de/>
#
# This file is part of Castellum.
#
# Castellum is free software; you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# Castellum is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License along with Castellum. If not, see
# <http://www.gnu.org/licenses/>.

from django.conf import settings
from django.contrib import admin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LogoutView
from django.http import HttpResponse
from django.urls import include
from django.urls import path
from django.views.generic import RedirectView
from django.views.generic import TemplateView
from django.views.i18n import JavaScriptCatalog

from mfa.decorators import public as mfa_public
from mfa.views import LoginView
from stronghold.decorators import public

from castellum.castellum_auth.forms import AuthenticationForm
from castellum.castellum_auth.views import set_language
from castellum.execution.views import ExecutionProtectedMediaView
from castellum.execution.views import StudyConsentProtectedMediaView
from castellum.recruitment.views import RecruitmentProtectedMediaView
from castellum.studies.models import Resource
from castellum.studies.models import Study
from castellum.studies.views.studies import StudyProtectedMediaView
from castellum.subjects.views import SubjectProtectedMediaView
from castellum.utils.views import ProtectedMediaView


class IndexView(LoginRequiredMixin, TemplateView):
    template_name = 'index.html'


class FeedsView(LoginRequiredMixin, TemplateView):
    template_name = 'feeds.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['resources'] = Resource.objects.all()
        context['studies'] = self.request.user.study_set.filter(status=Study.EXECUTION)
        return context


def dummy(request):
    return HttpResponse('', status=204)


urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('login/', LoginView.as_view(
        template_name="login.html",
        authentication_form=AuthenticationForm,
    ), name='login'),
    path('logout/', mfa_public(LogoutView.as_view()), name='logout'),
    path('favicon.ico', mfa_public(public(RedirectView.as_view(url='/static/images/favicon.ico')))),
    path('theme.css', mfa_public(public(TemplateView.as_view(
        template_name='bootstrap_theme.css',
        content_type='text/css',
    ))), name='bootstrap-theme'),
    path('ping/', dummy, name='ping'),
    path('feeds/', FeedsView.as_view(), name='feeds'),

    path('i18n/', mfa_public(set_language), name='set_language'),
    path('jsi18n/', mfa_public(public(JavaScriptCatalog.as_view())), name='javascript-catalog'),

    path('admin/', admin.site.urls),
    path('studies/', include('castellum.studies.urls', namespace='studies')),
    path('subjects/', include('castellum.subjects.urls', namespace='subjects')),
    path('contacts/', include('castellum.contacts.urls', namespace='contacts')),
    path('recruitment/', include('castellum.recruitment.urls', namespace='recruitment')),
    path('execution/', include('castellum.execution.urls', namespace='execution')),
    path('', include('castellum.appointments.urls', namespace='appointments')),
    path(
        'data-protection/', include('castellum.data_protection.urls', namespace='data_protection')
    ),
    path('mfa/', include('mfa.urls', namespace='mfa')),
]

if settings.PROTECTED_MEDIA_SERVER:
    urlpatterns += [
        path('media/studies/<int:pk>/<path:path>', StudyProtectedMediaView.as_view()),
        path(
            'media/recruitment/<int:study_pk>/<int:pk>/<path:path>',
            RecruitmentProtectedMediaView.as_view(),
            name='recruitment-media',
        ),
        path(
            'media/execution/<int:study_pk>/<int:pk>/<path:path>',
            ExecutionProtectedMediaView.as_view(),
            name='execution-media',
        ),
        path(
            'media/studyconsents/<int:study_pk>/<int:pk>/<filename>',
            StudyConsentProtectedMediaView.as_view(),
            name='studyconsent-media',
        ),
        path(
            'media/subjects/<uuid:uuid>/<path:path>',
            SubjectProtectedMediaView.as_view(),
            name='subject-media',
        ),
        path('media/consent/<path:path>', ProtectedMediaView.as_view(prefix='consent')),
    ]

if 'model_stats' in settings.INSTALLED_APPS:
    urlpatterns = [
        path('admin/stats/', include('model_stats.urls')),
    ] + urlpatterns

try:
    import debug_toolbar

    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]
except ImportError:
    pass

castellum/execution/forms.py
# (c) 2018-2023 MPIB <https://www.mpib-berlin.mpg.de/>,
#     2018-2019 MPI-CBS <https://www.cbs.mpg.de/>,
#     2018-2019 MPIP <http://www.psych.mpg.de/>
#
# This file is part of Castellum.
#
# Castellum is free software; you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# Castellum is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License along with Castellum. If not, see
# <http://www.gnu.org/licenses/>.

from django import forms
from django.utils.translation import gettext_lazy as _


class NewsMailForm(forms.Form):
    subject = forms.CharField(label=_('E-mail subject'), required=True)
    body = forms.CharField(
        label=_('E-mail body'),
        help_text=_(
            'Any "{name}"-tags included in the e-mail-body will '
            'automatically be replaced with the full name of the subject.'
        ),
        widget=forms.Textarea,
        required=True,
    )

castellum/execution/templates/execution/base.html
{% extends "base_with_breadcrumbs.html" %}

{% load i18n %}

{% block breadcrumbs %}
    <li class="breadcrumb-item"><a href="{% url 'studies:index' %}">{% translate "Studies" %}</a></li>
    {% if study %}
        <li class="breadcrumb-item"><a {% if study.status == study.EXECUTION %}href="{% url 'execution:participation-list' study.pk %}"{% endif %}>{% translate 'Execution for' %} {{ study.name }}</a></li>
    {% endif %}
    {% if participation %}
        <li class="breadcrumb-item"><a {% if study.status == study.EXECUTION %}href="{% url 'execution:participation-detail' study.pk participation.pk %}"{% endif %}>{{ participation.subject.contact.short_name }}</a></li>
    {% endif %}
{% endblock %}

castellum/execution/templates/execution/calendar.html
{% extends "execution/study_base.html" %}
{% load static %}

{% block container_class %}container-lg{% endblock%}

{% block content %}
    <div class="my-5" data-js="calendar"></div>
{% endblock %}

{% block extra_scripts %}
    <script src="{% static 'fullcalendar-scheduler/main.js' %}"></script>
    <script src="{% static 'fullcalendar-scheduler/locales/de.js' %}"></script>
    <script src="{% static 'js/calendar.js' %}"></script>
{% endblock %}

{% block extra_styles %}
    <link rel="stylesheet" type="text/css" href="{% static 'fullcalendar-scheduler/main.css' %}">
{% endblock %}

castellum/execution/templates/execution/participation_base.html
{% extends "execution/base.html" %}
{% load i18n auth utils %}

{% block title %}{{ study }} &middot; {{ block.super }}{% endblock %}

{% block header %}
    <div class="container text-center my-4">
        <h1>
            <svg class="identicon" data-jdenticon-value="{{ participation.pk }}" aria-hidden="true"></svg>
            {{ subject.contact.full_name }}
        </h1>
        {% for tag in participation.execution_tags.all %}
            <span class="badge text-bg-{{ tag.color }}">{{ tag }}</span>
        {% endfor %}
        {% if participation.dropped_out %}
            <span class="badge text-bg-secondary" title="{{ participation.TOOLTIPS.dropped_out }}">{{ participation|verbose_name:'dropped_out' }}</span>
        {% endif %}
        {% if not subject.is_available %}
            <span class="list-icon text-bg-warning" title="{% blocktranslate with next_available=subject.not_available_until %}not available until {{ next_available }}{% endblocktranslate %}">{% icon 'phone-slash' %}</span>
        {% endif %}
    </div>

    <nav class="d-print-none" aria-label="{% translate 'Tabs' %}">
        <ul class="nav nav-tabs justify-content-center mb-3">
            <li class="nav-item">
                <a href="{% url 'execution:participation-detail' study.pk participation.pk %}" class="nav-link {% if view.tab == 'overview' %}active{% endif %}">{% translate 'Overview' %}</a>
            </li>
            <li class="nav-item">
                <a href="{% url 'execution:participation-consent' study.pk participation.pk %}" class="nav-link {% if view.tab == 'consent' %}active{% endif %}">{% translate 'Study consent' %}</a>
            </li>
            <li class="nav-item">
                <a href="{% url 'execution:participation-update' study.pk participation.pk %}" class="nav-link {% if view.tab == 'update' %}active{% endif %}">{% translate 'Hints' %}</a>
            </li>

            {% has_perm 'appointments.change_appointment' user study as can_change_appointment %}
            {% if can_change_appointment and study.studysession_set.exists %}
                <li class="nav-item">
                    <a href="{% url 'execution:participation-appointments' study.pk participation.pk %}" class="nav-link {% if view.tab == 'appointments' %}active{% endif %}">{% translate 'Appointments' %}</a>
                </li>
            {% endif %}

            {% has_perm 'subjects.change_subject' user study as can_change_subject %}
            {% if can_change_subject %}
                <li class="nav-item">
                    <a href="{% url 'execution:contact-update' study.pk participation.pk %}" class="nav-link {% if view.tab == 'update-data' %}active{% endif %}">
                        {% if subject.consent_action_required or not subject.contact.is_complete %}
                            {% icon 'exclamation-triangle' label=_('Action required') %}
                        {% endif %}
                        {% translate 'Update data' %}
                    </a>
                </li>
            {% endif %}
        </ul>
    </nav>
{% endblock %}

castellum/execution/templates/execution/participation_consent_change.html
{% extends "execution/participation_base.html" %}
{% load static i18n django_bootstrap5 %}

{% block title %}
    {% translate "Change study consent" %} &middot; {{ block.super }}
{% endblock %}

{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% include 'utils/form_errors.html' with form=form %}
        {% csrf_token %}

        {% bootstrap_field form.consent %}

        <div class="d-print-none mb-3">
            <a href="{{ view.get_success_url }}" class="btn btn-outline-primary" data-js="cancel">{% translate 'Cancel' %}</a>
            <button class="btn btn-primary">{% translate 'Save' %}</button>
        </div>
    </form>
{% endblock %}

castellum/execution/templates/execution/participation_dropout.html
{% extends "execution/participation_base.html" %}
{% load i18n %}

{% block title %}{% translate "Dropped out" context 'verb' %} &middot; {{ block.super }}{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <p>{% translate 'Do you want to mark this subject as "dropped out"? This may apply if the subject can no longer take part in the study or repeatedly did not show up for appoitments.' %}</p>
        <p>{% translate "In addition, you must decide what should happen with the data collected this far: If you plan to use the data, the participation must not be removed as this would also delete the pseudonyms. If you do not plan to use the data, delete all of it and then remove the participation." %}</p>

        <div class="card-group mb-3">
            <div class="card">
                <div class="card-body">
                    {% translate 'The subject will continue participating in this study.' %}
                </div>
                <div class="card-footer">
                    <button class="btn btn-primary d-block w-100" name="dropped_out" value="">{% translate 'Participate' %}</button>
                </div>
            </div>
            <div class="card">
                <div class="card-body">
                    {% translate 'The subject will no longer participate in this study, but the data collected so far will be used.' %}
                </div>
                <div class="card-footer">
                    <button class="btn btn-primary d-block w-100" name="dropped_out" value="1">{% translate 'Drop out' %}</button>
                </div>
            </div>
            <div class="card">
                <div class="card-body">
                    {% translate 'The subject will no longer participate in this study, and the data collected so far will not be used.' %}
                </div>
                <div class="card-footer">
                    <a class="btn btn-danger d-block w-100" href="{% url 'execution:participation-dropout-confirm' study.pk object.pk %}">{% translate 'Drop out' %}</a>
                </div>
            </div>
        </div>

        <div class="d-print-none mb-3">
            <a href="{% url 'execution:participation-detail' study.pk object.pk %}" class="btn btn-outline-primary">{% translate 'Cancel' %}</a>
        </div>
    </form>
{% endblock %}

castellum/execution/templates/execution/participation_dropout_confirm.html
{% extends "execution/participation_base.html" %}
{% load i18n %}

{% block title %}{% translate "Dropped out" context 'verb' %} &middot; {{ block.super }}{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <p>{% translate 'Are you sure you want to remove this participation?' %}</p>
        <label class="form-check">
            <input type="checkbox" class="form-check-input" data-js="confirm-delete">
            <span class="form-check-label">{% translate "I have made sure that all external data related to this study participation has been destroyed" %}</span>
        </label>
        <div class="d-print-none mb-3">
            <a href="{% url 'execution:participation-detail' study.pk object.pk %}" class="btn btn-outline-primary" data-js="cancel">{% translate 'Cancel' %}</a>
            <button class="btn btn-danger" disabled>{% translate 'Confirm' %}</button>
        </div>
    </form>
{% endblock %}

castellum/execution/templates/execution/participation_hints.html
{% extends "execution/participation_base.html" %}
{% load i18n django_bootstrap5 %}

{% block content %}
    <form method="post">
        {% include 'utils/form_errors.html' with form=form %}
        {% csrf_token %}

        {% bootstrap_field form.news_interest %}
        {% bootstrap_field form.was_reliable %}

        {% if study.executiontag_set.exists %}
            <div class="mb-3">
                {{ form.execution_tags.label }}

                {% for value, label in form.execution_tags.field.choices %}
                    <label class="form-check mb-0">
                        <input type="checkbox" class="form-check-input" name="execution_tags" value="{{ value }}" {% if value.instance.id in form.execution_tags.value %}checked{% endif %}>
                        <span class="form-check-label">
                            <span class="badge text-bg-{{ value.instance.color }}">{{ label }}</span>
                        </span>
                    </label>
                {% endfor %}
                <small><a href="{% url 'execution:execution-tags' study.pk %}">{% translate 'Manage tags' %}</a></small>
            </div>
        {% endif %}

        <button class="btn btn-primary">{% translate 'Save' %}</button>
    </form>
{% endblock %}

castellum/execution/templates/execution/participation_list.html
{% extends "execution/study_base.html" %}
{% load i18n auth utils %}

{% block content %}
    {% if sort_options|length > 1 %}
        <div class="d-flex justify-content-end">
            <form class="dropdown" method="get">
                <button class="btn btn-outline-primary dropdown-toggle" type="button" id="sortDropdownButton" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {{ sort_label }}
                </button>
                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="sortDropdownButton">
                    {% for key, label in sort_options %}
                        <button class="dropdown-item" name="sort" value="{{ key }}">
                            {% if label.color %}
                                <span class="badge text-bg-{{ label.color }}">{{ label }}</span>
                            {% else %}
                                {{ label }}
                            {% endif %}
                        </button>
                    {% endfor %}
                </div>
            </form>
        </div>
    {% endif %}
    <ul class="table-list mt-3">
        {% for participation in object_list %}
            <li class="table-list-item">
                {% has_privacy_level participation.subject.privacy_level user as can_access %}
                {% if can_access %}
                    <svg class="identicon my-1 me-2" data-jdenticon-value="{{ participation.pk }}" aria-hidden="true"></svg>
                    <div class="d-inline-block my-1 me-2 {% if participation.dropped_out or participation.subject.blocked or participation.subject.deceased %}text-muted{% endif %}">
                        <div>
                            {{ participation.subject.contact.full_name }}
                            {% if participation.subject.privacy_level > 0 %}
                                <span class="badge {% if participation.subject.privacy_level > study.members_min_privacy_level %}text-bg-warning{% else %}text-bg-secondary{% endif %}">
                                    {% icon 'user-shield' label=_('Privacy level') %}
                                    {{ participation.subject.get_effective_privacy_level }}
                                    {% if participation.subject.privacy_level > study.members_min_privacy_level %}
                                        {% icon 'warning' label=_('Not all members of this study can access this subject') %}
                                    {% endif %}
                                </span>
                            {% endif %}
                            {% if session_count > 0 %}
                                <span class="badge text-bg-secondary my-1" title="{% blocktranslate with count=participation.appointment_count total=session_count %}{{ count }} out of {{ total }} appointments have already been scheduled{% endblocktranslate %}">
                                    {% icon 'calendar' label=_('Appointments') %}
                                    {{ participation.appointment_count }}/{{ session_count }}
                                    {% if participation.appointment_today %}
                                        {% translate 'today' %}
                                    {% endif %}
                                </span>
                            {% endif %}
                            {% for tag in participation.execution_tags.all %}
                                <span class="badge text-bg-{{ tag.color }} my-1">{{ tag }}</span>
                            {% endfor %}
                            {% if participation.dropped_out %}
                                <span class="badge text-bg-secondary my-1" title="{{ participation.TOOLTIPS.dropped_out }}">{{ participation|verbose_name:'dropped_out' }}</span>
                            {% endif %}
                            {% if participation.subject.blocked %}
                                <span class="badge text-bg-dark my-1" title="{{ participation.subject.TOOLTIPS.blocked }}">{{ participation.subject|verbose_name:'blocked' }}</span>
                            {% endif %}
                            {% if participation.subject.deceased %}
                                <span class="badge text-bg-dark my-1" title="{{ participation.subject.TOOLTIPS.deceased }}">{{ participation.subject|verbose_name:'deceased' }}</span>
                            {% endif %}
                        </div>
                    </div>
                    <div class="table-list-item-actions">
                        <a class="btn btn-outline-primary my-1" href="{% url 'execution:participation-detail' study.pk participation.pk %}">{% translate 'Details' %}</a>
                    </div>
                {% else %}
                    <div class="text-muted">
                        <div class="d-inline-block my-1 me-2">
                            {% translate 'insufficient privacy level' %}
                            <span class="list-icon text-bg-danger">{% icon 'ban' %}</span>
                        </div>
                    </div>
                {% endif %}
            </li>
        {% empty %}
            <li class="alert alert-warning">{% translate 'No participations found' %}</li>
        {% endfor %}
    </ul>
{% endblock %}

castellum/execution/templates/execution/participation_pseudonyms.html
{% extends "execution/participation_base.html" %}
{% load i18n utils %}

{% block title %}{% translate 'Pseudonyms' %} &middot; {{ block.super }}{% endblock %}

{% block header %}{% endblock %}

{% block content %}
    <table class="table">
        <thead>
            <tr>
                <th>{% translate 'Domain key' %}</th>
                <th>{% translate 'Domain name' %}</th>
                <th>{% translate 'Pseudonym' %}</th>
            </tr>
        </thead>
        <tbody>
            {% for domain in domains %}
                <tr>
                    <td>{{ domain|display:'key' }}</dt>
                    <td>{{ domain|display:'name' }}</dt>
                    <td>
                        <a href="{% url 'execution:participation-pseudonym' study.pk view.kwargs.pk domain.key %}" data-js="replace-me" class="btn btn-sm btn-secondary">
                            {% translate 'get pseudonym' %}
                        </a>
                    </dt>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="3"><em>{% translate 'No domains' %}</em></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

castellum/execution/templates/execution/participation_update_base.html
{% extends "execution/participation_base.html" %}
{% load i18n utils %}

{% block container_class %}container-lg{% endblock %}

{% block content_with_messages %}
    <div class="row">
        <div class="col-md-3">
            <nav class="list-group mb-3" aria-label="{% translate 'Subtabs' %}">
                <a class="list-group-item list-group-item-custom list-group-item-action {% if view.subtab == 'contact' %}active{% endif %}" href="{% url 'execution:contact-update' study.pk participation.pk %}">
                    {% if not subject.contact.is_complete %}
                        {% icon 'exclamation-triangle' label=_('Action required') %}
                    {% endif %}
                    {% translate 'Contact' %}
                </a>
                <a class="list-group-item list-group-item-custom list-group-item-action {% if view.subtab == 'attributes' %}active{% endif %}" href="{% url 'execution:attributes-update' study.pk participation.pk %}">{% translate 'Recruitment attributes' %}</a>
                <a class="list-group-item list-group-item-custom list-group-item-action {% if view.subtab == 'data-protection' %}active{% endif %}" href="{% url 'execution:data-protection-update' study.pk participation.pk %}">
                    {% if subject.consent_action_required %}
                        {% icon 'exclamation-triangle' label=_('Action required') %}
                    {% endif %}
                    {% translate 'Data protection' %}
                </a>
                <a class="list-group-item list-group-item-custom list-group-item-action {% if view.subtab == 'additional-info' %}active{% endif %}" href="{% url 'execution:additional-info-update' study.pk participation.pk %}">
                    {% translate 'Additional Info' %}
                </a>
            </nav>
        </div>

        <div class="col-md-9">
            {{ block.super }}
        </div>
    </div>
{% endblock %}

castellum/execution/templates/execution/study_export.html
{% extends "execution/study_base.html" %}
{% load i18n django_bootstrap5 %}

{% block title %}{% translate 'Export' %} &middot; {{ block.super }}{% endblock %}

{% block content %}
    <form method="get">
        {% include 'utils/form_errors.html' with form=form %}
        {% bootstrap_field form.domain %}
        <button class="btn btn-primary">{% translate 'Export' %}</button>
    </form>
{% endblock %}